### ISSUE TITLE
Ror some books not able to create epub only zip is created

### ISSUE THREAD

**Issue by dhruv-bansal** [ViciousPotato/safaribooks#14]
Ror some books not able to create epub only zip is created, like try book number 9780080568782

**Comment by PoHsun-Su** [comment]
Invalid filename 'TCP/IP_Sockets_in_Java-9780080568782.epub'
since forward slash is one of the reserved characters.
#15 can fix the issue

**Comment by ViciousPotato** [comment]
Tested fixed by #15. Close.
