### ISSUE TITLE
login failed error

### ISSUE THREAD

**Issue by dhruv-bansal** [ViciousPotato/safaribooks#16]
i have created new username password. i am able to login on the web portal but same credentials giving login failed error via this utility.
username: smilingstar023@gmail.com
password: test23

same credentials are working on web portal

**Comment by ViciousPotato** [comment]
@dhruv-bansal Hi the example account provided is new account type for me, and I have fixed the problem.

Could you update  the code and try again?

**Comment by ViciousPotato** [comment]
Marked as fixed if no other issue.
