### ISSUE TITLE
command not found 

### ISSUE THREAD

**Issue by wahajs00** [ViciousPotato/safaribooks#20]
./crawl.sh username my password  bookid
./crawl.sh: line 8: scrapy: command not found
./crawl.sh: line 9: kindlegen: command not found
im using ubuntu 17 
if i type this 
wahhaj@wahhaj:~/Desktop/safaribooks/safaribooks$ ./crawl.sh 
Please give a pure digit book id,  is not an acceptable book id.
error i have check the book id 3 times it doesnt work

**Comment by ViciousPotato** [comment]
Hi @wahajs00 have you tried install the pre-requirements? It seems scrapy is not installed.

**Comment by wahajs00** [comment]
yh sorry i actually fix this issue scrapy was not installed correctly
