### ISSUE TITLE
book_id should not be an int because it can have a leading zero

### ISSUE THREAD

**Issue by atse** [ViciousPotato/safaribooks#24]
https://github.com/ViciousPotato/safaribooks/blob/8ae51af5a3fb847766f5836b226a8fbf4ec6cac9/safaribooks/__main__.py#L78-L83

For example when the book ID is **`0596528124`** or **`"0596528124"`**, the leading **`0`** is dropped when casting as `int`. This results in a 404:

> 2018-01-25 18:26:01 [scrapy.core.engine] DEBUG: Crawled (404) <GET https://www.safaribooksonline.com/nest/epub/toc/?book_id=596528124> (referer: https://www.safaribooksonline.com/home/)

The correct URL has a leading `0` in `book_id`:
https://www.safaribooksonline.com/nest/epub/toc/?book_id=0596528124

**Comment by wnds** [comment]
Fixed in #22

**Comment by ViciousPotato** [comment]
Thank you @wnds verified works!
