### ISSUE TITLE
Cant install it!

### ISSUE THREAD

**Issue by Gamartto** [ViciousPotato/safaribooks#25]
Hi, I don't know what am I doing wrong but when I run the command "pip install safaribooks" on a freshly installed copy of python 2.7 (python-2.7.14) on a Win10 machine I get the message:

Collecting safaribooks
  Could not find a version that satisfies the requirement safaribooks (from versions: )
No matching distribution found for safaribooks

What could be the issue that prevents me from installing this software?

Thanks.

**Comment by dennissheppard** [comment]
I got the same issue and was able to install using `pip install git+https://github.com/ViciousPotato/safaribooks.git`.

Unfortunately, while it installed, it still doesn't work. Once that finished and I run `safaribooks` with my parameters, I get the error `KeyError: 'Spider not found: SafariBooks'`

**Comment by Gamartto** [comment]
Hmm that command doesn't work either

**Comment by dennissheppard** [comment]
Same error?

**Comment by dennissheppard** [comment]
I literally just ran it 20 mins ago and it worked. Again, doesn't seem to matter, though...

**Comment by Gamartto** [comment]
Collecting git+https://github.com/ViciousPotato/safaribooks.git
  Cloning https://github.com/ViciousPotato/safaribooks.git to c:\users\<myusername>\appdata\local\temp\pip-jm1bcx-build
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/ViciousPotato/safaribooks.git c:\users\<myusername>\appdata\local\temp\pip-jm1bcx-build
Cannot find command 'git'


That's the error.

**Comment by Gamartto** [comment]
Thanks, I was able to install it using your command.
