### ISSUE TITLE
Support for SSO accounts

### ISSUE THREAD

**Issue by hb3b** [ViciousPotato/safaribooks#6]
It would be great if this supported SSO accounts.
https://www.safaribooksonline.com/enterprise/

**Comment by himanshuvirmani** [comment]
+1

**Comment by antoinedesbois** [comment]
+1

**Comment by sivanes** [comment]
Yes please!

**Comment by mifas** [comment]
@wnds I've tried your PR, could you give an example how to use cookie, I've tried with EditThisCookie

**Comment by wnds** [comment]
<img width="879" alt="screenshot 2018-01-31 21 23 20" src="https://user-images.githubusercontent.com/1936503/35632614-23eeadaa-06cd-11e8-8f1a-66325520bcdf.png">

Paste curl request in a plain text editor and copy cookie header. It should appear as "-H 'cookie:". Copy cookie value and provide as -c/--cookie argument within single quotes.

**Comment by harpratap** [comment]
@wnds 
```
Traceback (most recent call last):
  File "/usr/local/bin/safaribooks", line 11, in <module>
    load_entry_point('safaribooks', 'console_scripts', 'safaribooks')()
  File "/app/safaribooks/__main__.py", line 121, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
The SSO cookie has an email parameter with double quotes, maybe that is causing the issue?

**Comment by hb3b** [comment]
Fantastic, working great here. Thanks.

**Comment by wnds** [comment]
@harpratap I checked mine and email is in double quote as well. However I was able to download book.

**Comment by harpratap** [comment]
@wnds Thanks, it works. Was missing an argument.
