### ISSUE TITLE
true not define + small improvement

### ISSUE THREAD

**Issue by dansasca** [ViciousPotato/safaribooks#8]
Hi,

I received an error about true not being defined so I added it in ./safaribook/spiders/safaribooks.py just after false:

Line     16 false = False
Line     17 true = True

Because I was getting 2 files with similar path I also added bookid to the name of the epub file:

Line    107     shutil.move(self.book_name + '.zip', self.book_name+'-'+ self.bookid + '.epub')
 
Line 107 was originally 106, but after inserting true at line 17 as above it changed.

Hope this helps,
Dan

**Comment by ViciousPotato** [comment]
Thank you for the suggestion, it helps a lot!
